name: Extract package.xml version
description: Extract <version> tag from package.xml

outputs:
  version:
    description: Extracted version from package.xml

runs:
  using: composite
  steps:
    - name: Run Python version extractor
      run: python3 ${{ github.action_path }}/extract_version.py
      shell: bash

    - name: Set step output
      run: |
        VERSION=$(cat version.txt)
        echo "version=$VERSION" >> $GITHUB_OUTPUT
      shell: bash
