name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Extract version
        id: version
        run: python3 ./.github/scripts/extract_version.py

      - name: Show extracted versions
        run: |
          echo "Full version: ${{ steps.version.outputs.version_full }}"
          echo "Major.Minor: ${{ steps.version.outputs.version_minor }}"
          echo "Major only: ${{ steps.version.outputs.version_major }}"